[package]
name = "nanogptrs"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
tch_download = ["tch/default"]

[dependencies]
tch = { version = "0.11.0", default-features = false, features = [] }
rand = "0.8.5"
rand_chacha = "0.3.1"

[dev-dependencies]
rand_chacha = "0.3.1"