name: nanogptrs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
    - safetensors
    - torch
    - tokenizers
    - tensorboard
