[env]
LIBTORCH_USE_PYTORCH = {"value"="1"} 
LIBTORCH_BYPASS_VERSION_CHECK = {"value"="1"} 

[profile.ci]
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.ci.junit]
path = "junit.xml"

[build]
rustflags = ["-W", "missing_docs"]

[target.'cfg(all())']
rustflags = [
    "-Dunsafe_code",
    "-Wmissing_docs",
    "-Wclippy::all",
    "-Wclippy::await_holding_lock",
    "-Wclippy::char_lit_as_u8",
    "-Arustdoc::invalid_rust_codeblocks",
    "-Arustdoc::bare_urls",
]

[target.'cfg(feature = "cargo-clippy")']
rustflags = ["-Wmissing_docs"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-shlib-undefined", "-C", "link-arg=-fno-lto"]