name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install lld
      run: sudo apt-get update && sudo apt-get install -y lld wget unzip
    - name: Download libtorch
      env:
        PYTORCH_VERSION: 2.0.0
      run: wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip -O /tmp/libtorch.zip
    - name: Install libtorch
      run: sudo unzip /tmp/libtorch.zip -d / && sudo cp /libtorch/lib/* /usr/lib/
    - uses: actions/checkout@v2
    - name: Setup symlink
      run: ln -s /libtorch $GITHUB_WORKSPACE/torch
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Debug
      run: ldd /usr/lib/libtorch_cpu.so
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
