name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install lld
      run: sudo apt-get update && sudo apt-get install -y lld wget unzip
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        generate-run-shell: true
        environment-file: environment.yml    
    - name: Download models
      run: ./models/download.sh
    - name: Download data
      run: ./data/download.sh
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Check
      run: |
        export LD_LIBRARY_PATH=`python -c "from torch.utils import cpp_extension; print(':'.join(cpp_extension.library_paths()))"`:$LD_LIBRARY_PATH
        cargo check
      shell: micromamba-shell {0}
    - name: Clippy
      run: |
        export LD_LIBRARY_PATH=`python -c "from torch.utils import cpp_extension; print(':'.join(cpp_extension.library_paths()))"`:$LD_LIBRARY_PATH
        cargo clippy -- -D warnings
      shell: micromamba-shell {0}
    - name: Build
      run: |
        export LD_LIBRARY_PATH=`python -c "from torch.utils import cpp_extension; print(':'.join(cpp_extension.library_paths()))"`:$LD_LIBRARY_PATH
        cargo build
      shell: micromamba-shell {0}
    - name: Test debug
      run: |
        ls /home/runner/micromamba/lib/
        find / -name "libcblas*" -type f 2>/dev/null
    - name: Test
      run: |
        export LD_LIBRARY_PATH=`python -c "from torch.utils import cpp_extension; print(':'.join(cpp_extension.library_paths()))"`:/home/runner/micromamba/lib/:$LD_LIBRARY_PATH
        cargo test
      shell: micromamba-shell {0}
